//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URPSSPSuccessTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprod-wsw.temple.edu/ws_ldapsearch/ldap_search.asmx")]
        public string URPSSPSuccessTracker_WS_LDAP_Search_LDAP_Search {
            get {
                return ((string)(this["URPSSPSuccessTracker_WS_LDAP_Search_LDAP_Search"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprod-wsw.temple.edu/programsanddegrees/ProgramsAndDegrees.asmx")]
        public string URPSSPSuccessTracker_WS_Programs_And_Degrees_ProgramsAndDegrees {
            get {
                return ((string)(this["URPSSPSuccessTracker_WS_Programs_And_Degrees_ProgramsAndDegrees"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprod-wsw.temple.edu/ws_student/ws_student.asmx")]
        public string URPSSPSuccessTracker_WS_Student_Search_WS_Student {
            get {
                return ((string)(this["URPSSPSuccessTracker_WS_Student_Search_WS_Student"]));
            }
        }
    }
}
