//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace URPSSPSuccessTracker.WS_LDAP_Search {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LDAP_SearchSoap", Namespace="http://wsw.temple.edu/")]
    public partial class LDAP_Search : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LDAP_Search() {
            this.Url = global::URPSSPSuccessTracker.Properties.Settings.Default.URPSSPSuccessTracker_WS_LDAP_Search_LDAP_Search;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsw.temple.edu/Search", RequestNamespace="http://wsw.temple.edu/", ResponseNamespace="http://wsw.temple.edu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TempleLDAPEntry[] Search(string username, string password, string attribute, string value) {
            object[] results = this.Invoke("Search", new object[] {
                        username,
                        password,
                        attribute,
                        value});
            return ((TempleLDAPEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string username, string password, string attribute, string value) {
            this.SearchAsync(username, password, attribute, value, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string username, string password, string attribute, string value, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        username,
                        password,
                        attribute,
                        value}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsw.temple.edu/")]
    public partial class TempleLDAPEntry {
        
        private string templeEduTUIDField;
        
        private string cnField;
        
        private string givenNameField;
        
        private string snField;
        
        private string uidField;
        
        private string eduPersonAffiliationField;
        
        private string eduPersonPrimaryAffiliationField;
        
        private string titleField;
        
        private string mailField;
        
        private string errorField;
        
        private string creatorsNameField;
        
        private string displayNameField;
        
        private string gidNumberField;
        
        private string homeDirectoryField;
        
        private string lField;
        
        private string loginShellField;
        
        private string mailAlternateAddressField;
        
        private string mailHostField;
        
        private string mailRoutingAddressField;
        
        private ManagerLDAPEntry managerField;
        
        private string modifiersNameField;
        
        private string modifyTimestampField;
        
        private string oField;
        
        private string objectClassField;
        
        private string ouField;
        
        private string postOfficeBoxField;
        
        private string postalAddressField;
        
        private string telephoneNumberField;
        
        private string templeEduAccountField;
        
        private string templeEduDateOfBirthField;
        
        private string templeEduDepartmentPhoneField;
        
        private string templeEduEmployeeDepartmentField;
        
        private string templeEduEmployeeDepartmentCodeField;
        
        private string templeEduGivenNameField;
        
        private string templeEduJobClassField;
        
        private string templeEduNamePrefixField;
        
        private string templeEduOrganizationCodeField;
        
        private string templeEduPrimaryOUField;
        
        private string templeEduPrimaryOUCodeField;
        
        private string templeEduSNField;
        
        private string templeEduTUCountryField;
        
        private string templeEduTUNAField;
        
        private string templeEduTUNICField;
        
        private string templeEduTUStPrField;
        
        private string templeEduTUStreetField;
        
        private string templeEduTUZPCField;
        
        private string templeEduWorkPhoneField;
        
        private string uidNumberField;
        
        /// <remarks/>
        public string templeEduTUID {
            get {
                return this.templeEduTUIDField;
            }
            set {
                this.templeEduTUIDField = value;
            }
        }
        
        /// <remarks/>
        public string cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
        
        /// <remarks/>
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string eduPersonAffiliation {
            get {
                return this.eduPersonAffiliationField;
            }
            set {
                this.eduPersonAffiliationField = value;
            }
        }
        
        /// <remarks/>
        public string eduPersonPrimaryAffiliation {
            get {
                return this.eduPersonPrimaryAffiliationField;
            }
            set {
                this.eduPersonPrimaryAffiliationField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string creatorsName {
            get {
                return this.creatorsNameField;
            }
            set {
                this.creatorsNameField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string gidNumber {
            get {
                return this.gidNumberField;
            }
            set {
                this.gidNumberField = value;
            }
        }
        
        /// <remarks/>
        public string homeDirectory {
            get {
                return this.homeDirectoryField;
            }
            set {
                this.homeDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string l {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        public string loginShell {
            get {
                return this.loginShellField;
            }
            set {
                this.loginShellField = value;
            }
        }
        
        /// <remarks/>
        public string mailAlternateAddress {
            get {
                return this.mailAlternateAddressField;
            }
            set {
                this.mailAlternateAddressField = value;
            }
        }
        
        /// <remarks/>
        public string mailHost {
            get {
                return this.mailHostField;
            }
            set {
                this.mailHostField = value;
            }
        }
        
        /// <remarks/>
        public string mailRoutingAddress {
            get {
                return this.mailRoutingAddressField;
            }
            set {
                this.mailRoutingAddressField = value;
            }
        }
        
        /// <remarks/>
        public ManagerLDAPEntry manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        public string modifiersName {
            get {
                return this.modifiersNameField;
            }
            set {
                this.modifiersNameField = value;
            }
        }
        
        /// <remarks/>
        public string modifyTimestamp {
            get {
                return this.modifyTimestampField;
            }
            set {
                this.modifyTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string o {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        public string objectClass {
            get {
                return this.objectClassField;
            }
            set {
                this.objectClassField = value;
            }
        }
        
        /// <remarks/>
        public string ou {
            get {
                return this.ouField;
            }
            set {
                this.ouField = value;
            }
        }
        
        /// <remarks/>
        public string postOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        public string postalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string telephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduAccount {
            get {
                return this.templeEduAccountField;
            }
            set {
                this.templeEduAccountField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduDateOfBirth {
            get {
                return this.templeEduDateOfBirthField;
            }
            set {
                this.templeEduDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduDepartmentPhone {
            get {
                return this.templeEduDepartmentPhoneField;
            }
            set {
                this.templeEduDepartmentPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduEmployeeDepartment {
            get {
                return this.templeEduEmployeeDepartmentField;
            }
            set {
                this.templeEduEmployeeDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduEmployeeDepartmentCode {
            get {
                return this.templeEduEmployeeDepartmentCodeField;
            }
            set {
                this.templeEduEmployeeDepartmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduGivenName {
            get {
                return this.templeEduGivenNameField;
            }
            set {
                this.templeEduGivenNameField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduJobClass {
            get {
                return this.templeEduJobClassField;
            }
            set {
                this.templeEduJobClassField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduNamePrefix {
            get {
                return this.templeEduNamePrefixField;
            }
            set {
                this.templeEduNamePrefixField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduOrganizationCode {
            get {
                return this.templeEduOrganizationCodeField;
            }
            set {
                this.templeEduOrganizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduPrimaryOU {
            get {
                return this.templeEduPrimaryOUField;
            }
            set {
                this.templeEduPrimaryOUField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduPrimaryOUCode {
            get {
                return this.templeEduPrimaryOUCodeField;
            }
            set {
                this.templeEduPrimaryOUCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduSN {
            get {
                return this.templeEduSNField;
            }
            set {
                this.templeEduSNField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUCountry {
            get {
                return this.templeEduTUCountryField;
            }
            set {
                this.templeEduTUCountryField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUNA {
            get {
                return this.templeEduTUNAField;
            }
            set {
                this.templeEduTUNAField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUNIC {
            get {
                return this.templeEduTUNICField;
            }
            set {
                this.templeEduTUNICField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUStPr {
            get {
                return this.templeEduTUStPrField;
            }
            set {
                this.templeEduTUStPrField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUStreet {
            get {
                return this.templeEduTUStreetField;
            }
            set {
                this.templeEduTUStreetField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUZPC {
            get {
                return this.templeEduTUZPCField;
            }
            set {
                this.templeEduTUZPCField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduWorkPhone {
            get {
                return this.templeEduWorkPhoneField;
            }
            set {
                this.templeEduWorkPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string uidNumber {
            get {
                return this.uidNumberField;
            }
            set {
                this.uidNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsw.temple.edu/")]
    public partial class ManagerLDAPEntry {
        
        private string templeEduTUIDField;
        
        private string cnField;
        
        private string givenNameField;
        
        private string snField;
        
        private string uidField;
        
        private string eduPersonAffiliationField;
        
        private string eduPersonPrimaryAffiliationField;
        
        private string titleField;
        
        private string mailField;
        
        private string creatorsNameField;
        
        private string displayNameField;
        
        private string gidNumberField;
        
        private string homeDirectoryField;
        
        private string lField;
        
        private string loginShellField;
        
        private string mailAlternateAddressField;
        
        private string mailHostField;
        
        private string mailRoutingAddressField;
        
        private string modifiersNameField;
        
        private string modifyTimestampField;
        
        private string oField;
        
        private string objectClassField;
        
        private string ouField;
        
        private string postOfficeBoxField;
        
        private string postalAddressField;
        
        private string telephoneNumberField;
        
        private string templeEduAccountField;
        
        private string templeEduDateOfBirthField;
        
        private string templeEduDepartmentPhoneField;
        
        private string templeEduEmployeeDepartmentField;
        
        private string templeEduEmployeeDepartmentCodeField;
        
        private string templeEduGivenNameField;
        
        private string templeEduJobClassField;
        
        private string templeEduNamePrefixField;
        
        private string templeEduOrganizationCodeField;
        
        private string templeEduPrimaryOUField;
        
        private string templeEduPrimaryOUCodeField;
        
        private string templeEduSNField;
        
        private string templeEduTUCountryField;
        
        private string templeEduTUNAField;
        
        private string templeEduTUNICField;
        
        private string templeEduTUStPrField;
        
        private string templeEduTUStreetField;
        
        private string templeEduTUZPCField;
        
        private string templeEduWorkPhoneField;
        
        private string uidNumberField;
        
        /// <remarks/>
        public string templeEduTUID {
            get {
                return this.templeEduTUIDField;
            }
            set {
                this.templeEduTUIDField = value;
            }
        }
        
        /// <remarks/>
        public string cn {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
        
        /// <remarks/>
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string eduPersonAffiliation {
            get {
                return this.eduPersonAffiliationField;
            }
            set {
                this.eduPersonAffiliationField = value;
            }
        }
        
        /// <remarks/>
        public string eduPersonPrimaryAffiliation {
            get {
                return this.eduPersonPrimaryAffiliationField;
            }
            set {
                this.eduPersonPrimaryAffiliationField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string creatorsName {
            get {
                return this.creatorsNameField;
            }
            set {
                this.creatorsNameField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string gidNumber {
            get {
                return this.gidNumberField;
            }
            set {
                this.gidNumberField = value;
            }
        }
        
        /// <remarks/>
        public string homeDirectory {
            get {
                return this.homeDirectoryField;
            }
            set {
                this.homeDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string l {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        public string loginShell {
            get {
                return this.loginShellField;
            }
            set {
                this.loginShellField = value;
            }
        }
        
        /// <remarks/>
        public string mailAlternateAddress {
            get {
                return this.mailAlternateAddressField;
            }
            set {
                this.mailAlternateAddressField = value;
            }
        }
        
        /// <remarks/>
        public string mailHost {
            get {
                return this.mailHostField;
            }
            set {
                this.mailHostField = value;
            }
        }
        
        /// <remarks/>
        public string mailRoutingAddress {
            get {
                return this.mailRoutingAddressField;
            }
            set {
                this.mailRoutingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string modifiersName {
            get {
                return this.modifiersNameField;
            }
            set {
                this.modifiersNameField = value;
            }
        }
        
        /// <remarks/>
        public string modifyTimestamp {
            get {
                return this.modifyTimestampField;
            }
            set {
                this.modifyTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string o {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        public string objectClass {
            get {
                return this.objectClassField;
            }
            set {
                this.objectClassField = value;
            }
        }
        
        /// <remarks/>
        public string ou {
            get {
                return this.ouField;
            }
            set {
                this.ouField = value;
            }
        }
        
        /// <remarks/>
        public string postOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        public string postalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string telephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduAccount {
            get {
                return this.templeEduAccountField;
            }
            set {
                this.templeEduAccountField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduDateOfBirth {
            get {
                return this.templeEduDateOfBirthField;
            }
            set {
                this.templeEduDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduDepartmentPhone {
            get {
                return this.templeEduDepartmentPhoneField;
            }
            set {
                this.templeEduDepartmentPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduEmployeeDepartment {
            get {
                return this.templeEduEmployeeDepartmentField;
            }
            set {
                this.templeEduEmployeeDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduEmployeeDepartmentCode {
            get {
                return this.templeEduEmployeeDepartmentCodeField;
            }
            set {
                this.templeEduEmployeeDepartmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduGivenName {
            get {
                return this.templeEduGivenNameField;
            }
            set {
                this.templeEduGivenNameField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduJobClass {
            get {
                return this.templeEduJobClassField;
            }
            set {
                this.templeEduJobClassField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduNamePrefix {
            get {
                return this.templeEduNamePrefixField;
            }
            set {
                this.templeEduNamePrefixField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduOrganizationCode {
            get {
                return this.templeEduOrganizationCodeField;
            }
            set {
                this.templeEduOrganizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduPrimaryOU {
            get {
                return this.templeEduPrimaryOUField;
            }
            set {
                this.templeEduPrimaryOUField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduPrimaryOUCode {
            get {
                return this.templeEduPrimaryOUCodeField;
            }
            set {
                this.templeEduPrimaryOUCodeField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduSN {
            get {
                return this.templeEduSNField;
            }
            set {
                this.templeEduSNField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUCountry {
            get {
                return this.templeEduTUCountryField;
            }
            set {
                this.templeEduTUCountryField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUNA {
            get {
                return this.templeEduTUNAField;
            }
            set {
                this.templeEduTUNAField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUNIC {
            get {
                return this.templeEduTUNICField;
            }
            set {
                this.templeEduTUNICField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUStPr {
            get {
                return this.templeEduTUStPrField;
            }
            set {
                this.templeEduTUStPrField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUStreet {
            get {
                return this.templeEduTUStreetField;
            }
            set {
                this.templeEduTUStreetField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduTUZPC {
            get {
                return this.templeEduTUZPCField;
            }
            set {
                this.templeEduTUZPCField = value;
            }
        }
        
        /// <remarks/>
        public string templeEduWorkPhone {
            get {
                return this.templeEduWorkPhoneField;
            }
            set {
                this.templeEduWorkPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string uidNumber {
            get {
                return this.uidNumberField;
            }
            set {
                this.uidNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TempleLDAPEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TempleLDAPEntry[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591